### ISSUE TITLE
how to fix it?tks

### ISSUE THREAD

**Issue by luckypoem** [adinapoli/alfredodinapoli.com#2]
hi.

root@AR:/usr/local/alfredodinapoli.com# ghc --make site.hs
[1 of 1] Compiling Main             ( site.hs, site.o )

site.hs:5:1: error:
    Failed to load interface for ‘Shelly’
    Use -v to see a list of the files searched for.
root@AR:/usr/local/alfredodinapoli.com#

**Comment by luckypoem** [comment]
or i do like this way,i still failed:

root@AR:/usr/local/alfredodinapoli.com# cabal sandbox init
root@AR:/usr/local/alfredodinapoli.com# cabal install

it shows:
...
Configuring hakyll-4.8.3.2...
Building hakyll-4.8.3.2...
Installed hakyll-4.8.3.2
Configuring website-1.2.0.0...
Building website-1.2.0.0...
Failed to install website-1.2.0.0
Build log ( /usr/local/alfredodinapoli.com/.cabal-sandbox/logs/website-1.2.0.0.log ):
cabal: Entering directory '.'
Configuring website-1.2.0.0...
Building website-1.2.0.0...
Preprocessing executable 'site' for website-1.2.0.0...
cabal: can't find source for Site in .
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
website-1.2.0.0 failed during the building phase. The exception was:
ExitFailure 1
root@AR:/usr/local/alfredodinapoli.com#

how to fix it?

**Comment by adinapoli** [comment]
Hey, using `stack` should work.

https://docs.haskellstack.org/en/stable/README/

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/alfredodinapoli.com# stack build

it shows:
...
pandoc-citeproc-0.7.4: download
pandoc-citeproc-0.7.4: configure
pandoc-citeproc-0.7.4: build
pandoc-citeproc-0.7.4: copy/register
hakyll-4.7.4.0: download
hakyll-4.7.4.0: configure
hakyll-4.7.4.0: build
hakyll-4.7.4.0: copy/register
website-1.2.0.0: configure
Configuring website-1.2.0.0...
website-1.2.0.0: build
Preprocessing executable 'site' for website-1.2.0.0...
setup-Simple-Cabal-1.22.4.0-ghc-7.10.2: can't find source for Site in .
Completed 128 action(s).

--  While building package website-1.2.0.0 using:
      /root/.stack/setup-exe-cache/i386-linux/setup-Simple-Cabal-1.22.4.0-ghc-7.10.2 --builddir=.stack-work/dist/i386-linux/Cabal-1.22.4.0 build exe:site exe:site-ctl --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
root@AR:/usr/local/alfredodinapoli.com# 

still not ok.how to fix it?

thank you.

**Comment by adinapoli** [comment]
Working just fine for me. I suggest deleting the repo locally and try again
on a clean-cloned repo with just “stack build” or “stack install”.

HTH.

**Comment by luckypoem** [comment]
hi.

root@AR:/usr/local/alfredodinapoli.com# stack install
website-1.2.0.0: configure
Configuring website-1.2.0.0...
website-1.2.0.0: build
Preprocessing library website-1.2.0.0...
In-place registering website-1.2.0.0...
Preprocessing executable 'site' for website-1.2.0.0...
setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: can't find source for Site in .

--  While building package website-1.2.0.0 using:
      /root/.stack/setup-exe-cache/i386-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/i386-linux/Cabal-1.22.5.0 build lib:website exe:site exe:site-ctl --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
root@AR:/usr/local/alfredodinapoli.com# cd ..
root@AR:/usr/local#

still not ok.
i recloned ur repo,and run "stack build",still encounter the above error.

or could u pls just upload the executable 'site' file to github.com?

**Comment by luckypoem** [comment]
at last i did it sucessfully.
cabal install shelly, then:
ghc --make site.hs

this time there is no error.

**Comment by adinapoli** [comment]
Glad it worked in the end!
